% Input is the output Excel file generated by individualDB.m
% Output is a boolean vector of if the subjects' individual DB proportions 
% match what is in their EGT_Analysis text files 

clear
excelPath = 'C:\Users\tmc54\Documents';
cd(excelPath)
excelFile = xlsread('rawSampleCountsSeperateDBsT2.xlsx'); % the output Excel file from individualDB.m
thePath = 'C:\Users\tmc54\Documents\EyeTracking\DukeACT_EGT\T2Background';
cd(thePath)
mainFolder = dir;
listOfSubjectFolders = {mainFolder(3:end).name}; 
[actressProportionCheck,toysProportionCheck,eyesProportionCheck,...
    mouthProportionCheck,sampleCountCheck] = ...
    deal(zeros(size(listOfSubjectFolders,2),1)); % preallocating

for folderNumber=1:size(listOfSubjectFolders,2) % run all subjects
    cd(thePath)
    subjectName = listOfSubjectFolders{folderNumber}(1:9);  %for DukeACT, pulls out just the subject name
    filename=[ subjectName '_EGT_Analysis.txt'];
    cd(subjectName);
    analysisFile = load(filename); % load the analysis text file into memory
    
    % Read every 10th entry until the end for each ROI target 
    monkeyCount = sum(excelFile(folderNumber, 2:10:end)); % monkey ROI is the 2nd column
    mooseCount = sum(excelFile(folderNumber, 3:10:end)); % moose ROI is the 3rd column
    roosterCount = sum(excelFile(folderNumber, 4:10:end)); % rooster ROI is the 4th column
    penguinCount = sum(excelFile(folderNumber, 5:10:end)); % penguin ROI is the 5th column
    
    handsCount = sum(excelFile(folderNumber, 6:10:end)); % hands ROI is the 6th column
    bodyCount = sum(excelFile(folderNumber, 7:10:end)); % body ROI is the 7th column
    eyesCount = sum(excelFile(folderNumber, 8:10:end)); % eye ROI is the 8th column
    mouthCount = sum(excelFile(folderNumber, 9:10:end)); % mouth ROI is the 9th column
    
    actressCount = mouthCount + eyesCount + bodyCount + handsCount; % actress ROI is the combination of mouth, eyes, body, and hands ROIs
    toysCount = monkeyCount + mooseCount + roosterCount + penguinCount; % toys ROI is the combination of monkey, moose, rooster, and penguin ROIs
    
    sampleCount = sum(excelFile(folderNumber, 1:10:end)); % total samples is the 1st column
    
    %% Calculate proportions 
    actressProportion = actressCount/sampleCount;
    toysProportion = toysCount/sampleCount;
    eyesProportion = eyesCount/sampleCount;
    mouthProportion = mouthCount/sampleCount;
    
    %% Compare proportions generated from Excel file to subject text file
    % Casting to strings and using strcmp because of rounding problems in
    % old versions of MATLAB
    actressProportionCheck(folderNumber) = strcmp(num2str(actressProportion), num2str(analysisFile(7)));
    toysProportionCheck(folderNumber) = strcmp(num2str(toysProportion), num2str(analysisFile(11)));
    eyesProportionCheck(folderNumber) = strcmp(num2str(eyesProportion), num2str(analysisFile(3)));
    mouthProportionCheck(folderNumber) = strcmp(num2str(mouthProportion), num2str(analysisFile(4)));
    sampleCountCheck(folderNumber) = strcmp(num2str(sampleCount), num2str(analysisFile(10)));
end

%% Calculate minimums of each proportion check
% If any of these values is not 1, proportions don't match up, need to look
% into that particular subject closely. 
output(1) = min(actressProportionCheck);
output(2) = min(toysProportionCheck);
output(3) = min(eyesProportionCheck);
output(4) = min(mouthProportionCheck);
output(5) = min(sampleCountCheck);